//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;// bunu ekledim Required için 


    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Satıslar = new HashSet<Satıslar>();
        }
    
        public int MusteriID { get; set; }
        [Required(ErrorMessage ="Müşteri Adını Giriniz")]// müşteri adın gerekli olduğu yani boş geçilemez yaptık ve hata mesajını buraya yazdırdım 
        [StringLength(50,ErrorMessage ="En Fazla 50 Karakter girebilirsiniz")]

        public string MusteriAdı { get; set; }
        public string MusteriSoyadı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satıslar> Satıslar { get; set; }
    }
}
